### ISSUE TITLE
process data problem

### ISSUE THREAD

**Issue by 489597448** [awslabs/gap-text2sql#3]
when i run  python run.py preprocess experiments/spider-configs/gap-run.jsonnet
erro:

Traceback (most recent call last):
  File "run.py", line 104, in <module>
    main()
  File "run.py", line 62, in main
    preprocess.main(preprocess_config)
  File "/home/lishuan/hxh/text2sql/gap-text2sql-main/rat-sql-gap/seq2struct/commands/preprocess.py", line 44, in main
    preprocessor.preprocess()
  File "/home/lishuan/hxh/text2sql/gap-text2sql-main/rat-sql-gap/seq2struct/commands/preprocess.py", line 23, in preprocess
    data = registry.construct('dataset', self.config['data'][section])
  File "/home/lishuan/hxh/text2sql/gap-text2sql-main/rat-sql-gap/seq2struct/utils/registry.py", line 36, in construct
    **kwargs)
  File "/home/lishuan/hxh/text2sql/gap-text2sql-main/rat-sql-gap/seq2struct/utils/registry.py", line 44, in instantiate
    raise ValueError('Unsupported kind for param {}: {}'.format(name, param.kind))
ValueError: Unsupported kind for param args: 2

**Comment by Impavidity** [comment]
Thanks for your interest on our work.

Did you try to follow the instruction to setup the environment?
What is the Python version you use? I assume it is 3.6.
You can try to use Python3.7 to see if you can solve this issue.

**Comment by 489597448** [comment]
> Thanks for your interest on our work.
> 
> Did you try to follow the instruction to setup the environment?
> What is the Python version you use? I assume it is 3.6.
> You can try to use Python3.7 to see if you can solve this issue.

my python version is Python 3.7.9

**Comment by Impavidity** [comment]
Did your try to setup the virtual environment from the command line we provided? Did that work for you?

**Comment by JoaoLages** [comment]
same problem. did you solve it?

**Comment by waytehsu** [comment]
same problem with virtual environment on python 3.7.10

**Comment by lezhu1234** [comment]
Here is a tricky slove:
change 
File "seq2struct/utils/registry.py", line 41, in
**signature = inspect.signature(callable)**
to
**signature = inspect.signature(callable.__init__)**

**Comment by alan-ai-learner** [comment]
@Impavidity  @lezhu1234 @JoaoLages @489597448 @waytehsu How much time will it take to preprocess the dataset, i was running the command for like past hours, it just keep running, can any one help me on this?
Thanks
